title: TIM TAWAN - Full Stack Developer
author: Tim Tawan
email: mrtawans@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tim Tawan, a full stack, React.js, React-Native, Node.js developer. 
  Working around JavaScript, Frontend-Backend Web Development.

github_username:  timtawan

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
